export const popupTemplates = {
  moderno: {
    name: "Moderno Minimalista",
    description: "Diseño limpio y minimalista con colores suaves y bordes redondeados",
    icon: "📍",
    colors: ["#3b82f6", "#1d4ed8"],
    size: {
      width: 340,
      minHeight: 240,
    },
    style: {
      background: "rgba(255, 255, 255, 0.98)",
      borderColor: "#e5e7eb",
      borderRadius: "16px",
      boxShadow: "0 20px 40px rgba(0,0,0,0.08), 0 8px 16px rgba(0,0,0,0.06)",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontSize: "13px",
      textColor: "#1f2937",
      header: {
        background: "linear-gradient(135deg, #3b82f6, #1d4ed8)",
        textColor: "#ffffff",
        padding: "16px 20px",
        fontSize: "14px",
        fontWeight: 600,
        borderBottom: "none",
      },
      section: {
        padding: "20px",
        gap: "8px",
      },
      separator: {
        height: "2px",
        background: "linear-gradient(90deg, transparent, #e5e7eb, transparent)",
        margin: "16px 0",
      },
      table: {
        width: "100%",
        borderCollapse: "separate",
        borderSpacing: "0 8px",
        fontSize: "13px",
      },
      tableRow: {
        borderBottom: "1px solid #f1f5f9",
        backgroundColor: "rgba(248, 250, 252, 0.5)",
      },
      tableLabel: {
        color: "#64748b",
        fontWeight: 500,
        padding: "12px 16px",
        width: "45%",
        textAlign: "left",
        borderLeft: "3px solid #3b82f6",
      },
      tableValue: {
        color: "#1e293b",
        fontWeight: 600,
        padding: "12px 16px",
        textAlign: "right",
      },
      footer: {
        background: "rgba(241, 245, 249, 0.8)",
        padding: "16px 20px",
        fontSize: "11px",
        color: "#64748b",
        textAlign: "center",
        borderTop: "1px solid #e2e8f0",
      },
    },
    layout: {
      sections: ["header", "content", "footer"],
      contentLayout: "table",
    },
  },

  corporativo: {
    name: "Corporativo Profesional",
    description: "Estilo empresarial formal con grises y diseño estructurado",
    icon: "💼",
    colors: ["#1f2937", "#374151"],
    size: {
      width: 400,
      minHeight: 280,
    },
    style: {
      background: "#ffffff",
      borderColor: "#d1d5db",
      borderRadius: "12px",
      boxShadow: "0 25px 50px rgba(0,0,0,0.12), 0 10px 20px rgba(0,0,0,0.08)",
      fontFamily: "Inter, system-ui, -apple-system, sans-serif",
      fontSize: "14px",
      textColor: "#111827",
      header: {
        background: "linear-gradient(135deg, #1f2937, #374151)",
        textColor: "#ffffff",
        padding: "20px 24px",
        fontSize: "16px",
        fontWeight: 600,
        borderBottom: "2px solid rgba(255,255,255,0.1)",
      },
      section: {
        padding: "24px",
        gap: "12px",
      },
      separator: {
        height: "3px",
        background: "linear-gradient(90deg, transparent, #e5e7eb, transparent)",
        margin: "20px 0",
      },
      table: {
        width: "100%",
        borderCollapse: "separate",
        borderSpacing: "0 12px",
        fontSize: "14px",
      },
      tableRow: {
        borderBottom: "2px solid #f8fafc",
        backgroundColor: "#ffffff",
        borderLeft: "4px solid transparent",
        borderRight: "4px solid transparent",
      },
      tableLabel: {
        color: "#6b7280",
        fontWeight: 600,
        padding: "16px 20px",
        width: "42%",
        textAlign: "left",
        borderLeft: "4px solid #1f2937",
        textTransform: "uppercase",
        fontSize: "12px",
        letterSpacing: "0.5px",
      },
      tableValue: {
        color: "#111827",
        fontWeight: 700,
        padding: "16px 20px",
        textAlign: "right",
        fontSize: "15px",
      },
      footer: {
        background: "linear-gradient(135deg, #f9fafb, #f3f4f6)",
        padding: "16px 24px",
        fontSize: "12px",
        color: "#6b7280",
        textAlign: "right",
        borderTop: "2px solid #e5e7eb",
        fontWeight: 500,
      },
    },
    layout: {
      sections: ["header", "content", "footer"],
      contentLayout: "table",
    },
  },

  colorido: {
    name: "Colorido Vibrante",
    description: "Diseño alegre y vibrante con gradientes multicolores y estilo moderno",
    icon: "🌈",
    colors: ["#ec4899", "#f59e0b", "#10b981"],
    size: {
      width: 380,
      minHeight: 260,
    },
    style: {
      background: "rgba(255, 255, 255, 0.99)",
      borderColor: "#fbbf24",
      borderRadius: "20px",
      boxShadow: "0 30px 60px rgba(0,0,0,0.15), 0 12px 24px rgba(0,0,0,0.1)",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      fontSize: "14px",
      textColor: "#1f2937",
      header: {
        background: "linear-gradient(135deg, #ec4899, #f59e0b, #10b981)",
        textColor: "#ffffff",
        padding: "20px 24px",
        fontSize: "16px",
        fontWeight: 700,
        borderBottom: "none",
      },
      section: {
        padding: "24px",
        gap: "12px",
      },
      separator: {
        height: "4px",
        background: "linear-gradient(90deg, #ec4899, #f59e0b, #10b981)",
        margin: "20px 0",
        borderRadius: "2px",
      },
      table: {
        width: "100%",
        borderCollapse: "separate",
        borderSpacing: "0 16px",
        fontSize: "14px",
      },
      tableRow: {
        borderBottom: "none",
        backgroundColor: "rgba(254, 243, 199, 0.3)",
        borderRadius: "12px",
        borderLeft: "5px solid transparent",
      },
      tableLabel: {
        color: "#92400e",
        fontWeight: 700,
        padding: "16px 20px",
        width: "45%",
        textAlign: "left",
        borderLeft: "5px solid #f59e0b",
        fontSize: "13px",
        textTransform: "uppercase",
        letterSpacing: "0.3px",
      },
      tableValue: {
        color: "#1f2937",
        fontWeight: 700,
        padding: "16px 20px",
        textAlign: "right",
        fontSize: "15px",
      },
      footer: {
        background: "linear-gradient(135deg, #fef3c7, #fde68a, #fed7aa)",
        padding: "20px 24px",
        fontSize: "12px",
        color: "#92400e",
        textAlign: "center",
        borderTop: "3px solid #f59e0b",
        fontWeight: 600,
      },
    },
    layout: {
      sections: ["header", "content", "footer"],
      contentLayout: "table",
    },
  },

  profesional: {
    name: "Profesional Premium",
    description: "Popup corporativo con diseño limpio, secciones claras y datos en tabla",
    icon: "🏢",
    colors: ["#4b5563", "#1f2937"],
    size: {
      width: 420,
      minHeight: 300,
    },
    style: {
      background: "linear-gradient(135deg, #f8fafc, #f1f5f9)",
      borderColor: "#d1d5db",
      borderRadius: "16px",
      boxShadow: "0 35px 70px rgba(0,0,0,0.15), 0 15px 30px rgba(0,0,0,0.1)",
      fontFamily: "Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
      fontSize: "14px",
      textColor: "#1f2937",
      header: {
        background: "linear-gradient(135deg, #4b5563, #1f2937)",
        textColor: "#ffffff",
        padding: "24px 28px",
        fontSize: "18px",
        fontWeight: 700,
        borderBottom: "3px solid rgba(255,255,255,0.2)",
        letterSpacing: "0.5px",
      },
      section: {
        padding: "28px",
        gap: "16px",
      },
      separator: {
        height: "3px",
        background: "linear-gradient(90deg, transparent, #cbd5e1, transparent)",
        margin: "24px 0",
        borderRadius: "2px",
      },
      table: {
        width: "100%",
        borderCollapse: "separate",
        borderSpacing: "0 14px",
        fontSize: "14px",
      },
      tableRow: {
        borderBottom: "2px solid #e2e8f0",
        backgroundColor: "#ffffff",
        borderRadius: "8px",
        boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
      },
      tableLabel: {
        color: "#64748b",
        fontWeight: 600,
        padding: "18px 24px",
        width: "38%",
        textAlign: "left",
        borderLeft: "5px solid #4b5563",
        textTransform: "uppercase",
        fontSize: "12px",
        letterSpacing: "0.8px",
      },
      tableValue: {
        color: "#0f172a",
        fontWeight: 700,
        padding: "18px 24px",
        textAlign: "right",
        fontSize: "16px",
      },
      footer: {
        background: "linear-gradient(135deg, #e2e8f0, #cbd5e1)",
        padding: "20px 28px",
        fontSize: "12px",
        color: "#475569",
        textAlign: "right",
        borderTop: "3px solid #94a3b8",
        fontWeight: 600,
        letterSpacing: "0.3px",
      },
    },
    layout: {
      sections: ["header", "content", "footer"],
      contentLayout: "table",
    },
  },
};